version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - wget -q https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip -O /tmp/terraform.zip
      - unzip -q /tmp/terraform.zip -d /tmp
      - mv /tmp/terraform /usr/local/bin/
      - terraform --version
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client
      - echo "Installing Helm..."
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - helm version

  pre_build:
    commands:
      - echo "========================================="
      - echo "ðŸ”‘ Logging into Amazon ECR..."
      - echo "========================================="
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/eks-analytics
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "âœ… ECR login successful"

  build:
    commands:
      - echo "========================================="
      - echo "ðŸ”¨ Building Lambda JAR..."
      - echo "========================================="
      - cd lambda/order-processor
      - mvn clean package -DskipTests
      - cd ../..
      - echo "âœ… Lambda JAR built"

      - echo "========================================="
      - echo "ðŸ”¨ Building EKS Analytics JAR..."
      - echo "========================================="
      - cd eks-analytics
      - mvn clean package -DskipTests
      - cd ..
      - echo "âœ… EKS Analytics JAR built"

      - echo "========================================="
      - echo "ðŸ³ Building Docker image..."
      - echo "========================================="
      - cd eks-analytics
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - cd ..
      - echo "âœ… Docker image built"

  post_build:
    commands:
      - echo "========================================="
      - echo "ðŸ“¤ Pushing Docker image to ECR..."
      - echo "========================================="
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "âœ… Docker image pushed"

      - echo "========================================="
      - echo "ðŸš€ Deploying with Terraform..."
      - echo "========================================="
      - cd terraform
      - terraform init
      - terraform apply -auto-approve -var="notification_email=swamyrapolu1@gmail.com" -var="repository_id=SwamyRa/orionflow-event-driven-order-processing-genai"
      - cd ..
      - echo "âœ… Terraform deployment complete"

      - echo "========================================="
      - echo "â˜¸ï¸ Deploying to EKS..."
      - echo "========================================="
      - aws eks update-kubeconfig --name order-processing-cluster-dev --region $AWS_DEFAULT_REGION
      - cd eks-analytics
      - helm upgrade --install eks-analytics ./helm --wait
      - kubectl patch svc eks-analytics -p '{"spec":{"type":"LoadBalancer"}}'
      - kubectl get svc eks-analytics
      - cd ..
      - echo "âœ… EKS deployment complete"

      - echo "========================================="
      - echo "ðŸ“ Writing image definitions..."
      - echo "========================================="
      - printf '[{"name":"eks-analytics","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "âœ… Build complete"

artifacts:
  files:
    - lambda/order-processor/target/order-processor-1.0.0.jar
    - imagedefinitions.json
    - eks-analytics/helm/**/*
